version: "3.4"
services:
  redis:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: my_master_password
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli" ,"ping"]
      start_period: 1s
      interval: 1s
      timeout: 5s
      retries: 99
